---
- name: >-
    The GitHub Pages destination is the branch name in the docs directory.
  set_fact:
    esdoc_gh_pages_dest: >-
      {{ esdoc_package_dir }}/{{ esdoc_doc_dir }}/{{ esdoc_gh_pages_branch }}

- name: >-
    Create the GitHub Pages dir at {{ esdoc_gh_pages_dest }}
  file:
    dest: "{{ esdoc_gh_pages_dest }}"
    state: directory

- name: >-
    Initialize Git repo at {{ esdoc_gh_pages_dest }}
  include_role:
    name: qb.git_repo
  vars:
    git_repo_dest: "{{ esdoc_gh_pages_dest }}"
    git_repo_gitignores:
    - Ruby
    - Jekyll

- name: >-
    Copy GitHub Pages files
  with_items:
  - _data/versions.yml
  - _layouts/default.html
  - Gemfile
  - index.md
  loop_control:
    loop_var: path
  copy:
    src: "{{ role_path }}/files/gh-pages/"
    dest: "{{ esdoc_gh_pages_dest }}"
    force: "{{ esdoc_force }}"

- name: >-
    Render templates
  with_items:
  - _config.yml.j2
  template:
    src: "{{ role_path }}/templates/gh-pages/{{ item }}"
    dest: "{{ esdoc_gh_pages_dest }}/{{ item | regex_replace('\\.j2$', '') }}"
    force: "{{ esdoc_force }}"

- name: >-
    Create versions directory
  file:
    dest: "{{ esdoc_gh_pages_dest }}/versions"
    state: directory

- name: >-
    Create v -> versions symlink
  file:
    src: versions/
    dest: "{{ esdoc_gh_pages_dest }}/v"
    state: link

- name: >-
    Throw a .gitkeep in versions so we have something to commit
  copy:
    dest: "{{ esdoc_gh_pages_dest }}/versions/.gitkeep"
    content: ''

# TODO doesn't work, not sure why... maybe rbenv BS?
# - name: >-
#     Install gh-pages gems
#   bundler:
#     state: present
#     chdir: "{{ esdoc_gh_pages_dest }}"
#     gem_path: ./.bundle

- name: >-
    Install gh-pages gems
  shell: bundle install --path=./.bundle
  args:
    chdir: "{{ esdoc_gh_pages_dest }}"

- name: >-
    Add everything to Git
  command: >-
    git add .
  args:
    chdir: "{{ esdoc_gh_pages_dest }}"

- name: >-
    Commit everything
  command: >-
    git commit -a -m "initial commit"
  args:
    chdir: "{{ esdoc_gh_pages_dest }}"

- name: >-
    Create {{ esdoc_gh_pages_branch }} branch
  command: >-
    git checkout -b {{ esdoc_gh_pages_branch }}
  args:
    chdir: "{{ esdoc_gh_pages_dest }}"

- name: >-
    Delete master branch
  command: >-
    git branch -d master
  args:
    chdir: "{{ esdoc_gh_pages_dest }}"

- name: >-
    Set git origin remote to {{ esdoc_gh_pages_branch }} branch of the main 
    repo's origin
  command: >-
    git remote add -t {{ esdoc_gh_pages_branch }} origin {{ esdoc_package_dir_facts.git.origin }}
  args:
    chdir: "{{ esdoc_gh_pages_dest }}"

- name: >-
    Push {{ esdoc_gh_pages_branch }} branch
  command: >-
    git push origin {{ esdoc_gh_pages_branch }}
  args:
    chdir: "{{ esdoc_gh_pages_dest }}"

- name: >-
    Remove the GitHub Pages directory
  file:
    dest: "{{ esdoc_gh_pages_dest }}"
    state: absent

- name: >-
    Add {{ esdoc_gh_pages_branch }} branch as submodule
  command: >-
    git submodule add
      -b {{ esdoc_gh_pages_branch }}
      {{ qb_git_origin_url }}
      doc/{{ esdoc_gh_pages_branch }}
  args:
    chdir: "{{ esdoc_package_dir }}"
