---
# tasks file for nrser.esdoc

- path_facts:
    path: "{{ esdoc_package_dir }}"
    github_api: true
  register: esdoc_package_dir_facts

- name: >-
    The GitHub Pages branch name is 'gh-pages' if the repo is public or
    'gh-pages-private' if it's private.
  set_fact:
    esdoc_gh_pages_branch: >-
      {%- if esdoc_package_dir_facts.git.github.private -%}
        gh-pages-private
      {%- else -%}
        gh-pages
      {%- endif -%}

- name: Add @nrser/esdoc package to devDependencies
  stream:
    cmd: yarn add --dev @nrser/esdoc
    chdir: "{{ esdoc_package_dir }}"
  when: >-
    not (
      '@nrser/esdoc'
      in esdoc_package_dir_facts.npm.package_json.devDependencies
    )

- name: Template in config/esdoc.js
  template:
    src: esdoc.js.j2
    dest: "{{ esdoc_package_dir }}/config/esdoc.js"
    force: "{{ esdoc_force }}"

- name: Include custom styles
  include: styles.yml
  when: esdoc_styles

- name: Include GitHub Pages / Jekyll site setup
  include: gh-pages.yml
  when: esdoc_gh_pages